### ISSUE TITLE
Benefits over "brew install util-linux" in 2023?

### ISSUE THREAD

**Issue by hartwork** [tzvetkoff/setsid-macosx#2]
Hi @tzvetkoff, thanks for making and sharing this code as Software Libre! :+1: 

Using Google I found that…

```bash
brew install util-linux
export PATH="${PATH}:/usr/local/opt/util-linux/bin"
```

…is also a way to get command `setsid` available on macOS today. Does your version of `setsid` offer benefits over util-linux' `setsid` on macOS in 2023? Would be great to know — thanks in advance! :pray: 

Best, Sebastian

**Comment by tzvetkoff** [comment]
Hi!

When I wrote (read: ported) this in my early days as an OSX user, I think `util-linux` wasn't part of `homebrew-core`.
I needed it to satisfy my own needs and never really cared much about it anything else.
I can see that now there is no need for a separate package, so I can happily archive this one.

Thanks for bringing this up!
